/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseConfirmDialog: typeof import('./src/components/base/BaseConfirmDialog.vue')['default']
    BaseDeleteDialog: typeof import('./src/components/base/BaseDeleteDialog.vue')['default']
    BaseDialog: typeof import('./src/components/base/BaseDialog.vue')['default']
    BaseDrawer: typeof import('./src/components/base/BaseDrawer.vue')['default']
    BaseExpandPanel: typeof import('./src/components/base/BaseExpandPanel.vue')['default']
    BaseFormSkeleton: typeof import('./src/components/share/BaseFormSkeleton.vue')['default']
    BaseLoadingSpinner: typeof import('./src/components/base/BaseLoadingSpinner.vue')['default']
    BasePagination: typeof import('./src/components/base/BasePagination.vue')['default']
    BaseTextField: typeof import('./src/components/base/BaseTextField.vue')['default']
    BaseToast: typeof import('./src/components/base/BaseToast.vue')['default']
    BillsFilter: typeof import('./src/components/billsManagement/BillsFilter.vue')['default']
    BillsForm: typeof import('./src/components/billsManagement/BillsForm.vue')['default']
    BillsHeader: typeof import('./src/components/billsManagement/BillsHeader.vue')['default']
    BillsTable: typeof import('./src/components/billsManagement/BillsTable.vue')['default']
    BillsView: typeof import('./src/components/billsManagement/BillsView.vue')['default']
    DropdownButton: typeof import('./src/components/base/DropdownButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowTableSkeleton: typeof import('./src/components/share/RowTableSkeleton.vue')['default']
  }
}
